[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
orderbook-core = { path = "../orderbook-core" }
axum = { version = "0.8.4" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3.31"
yawc = { version = "0.2.6", features = ["axum"] }
dirs = "5"

[lints]
workspace = true

[dev-dependencies]
rand = "0.9.1"
